name: flutter_base
description: Mr Milu's flutter base app.
publish_to: "none"

# We use the following build number guideline: yyyy+mm+dd+incremental
version: 0.0.1+202304051

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  browser_image_compression: 1.0.6
  cached_network_image: 3.3.1
  collection: 1.18.0
  cross_file: 0.3.3+8
  crypto: 3.0.3
  dio: 5.4.1
  easy_localization: 3.0.4
  extended_image: 8.2.0
  # version depends on flutter_mrmilu
  faker_dart: 0.1.11
  firebase_auth: 4.17.5
  firebase_core: 2.25.4
  firebase_dynamic_links: 5.4.14
  firebase_messaging: 14.7.16
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: 0.1.8
  flutter_config: 2.0.2
  flutter_dotenv: 5.1.0
  flutter_image_compress: 2.1.0
  flutter_local_notifications: 16.3.2
  flutter_mrmilu: 1.4.0
  flutter_native_splash: 2.3.13
  flutter_riverpod: 2.4.10
  flutter_secure_storage: 9.0.0
  flutter_svg: 2.0.9
  freezed_annotation: 2.4.1
  get_it: 7.6.7
  go_router: 13.2.0
  google_sign_in: 6.2.1
  image: 4.1.7
  image_editor: 1.3.0
  image_picker: 1.0.7
  injectable: 2.3.2
  json_annotation: 4.8.1
  package_info_plus: 5.0.1
  path_provider: 2.1.2
  reactive_forms: 16.1.1
  reactive_forms_annotations: 4.3.0
  riverpod: 2.5.0
  sentry_flutter: 7.16.1
  share_plus: 7.2.2
  sign_in_with_apple: 5.0.0
  stack_trace: 1.11.1
  video_player: 2.8.2

dev_dependencies:
  build_runner: 2.4.8
  flutter_flavorizr: 2.2.3
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.4.7
  injectable_generator: 2.4.1
  integration_test:
    sdk: flutter
  json_serializable: 6.7.1
  mocktail: 1.0.3
  reactive_forms_generator: 4.5.2

dependency_overrides:
  js: 0.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - .env.dev
    - .env.beta
    - .env.live

  fonts:
    - family: Recoleta
      fonts:
        - asset: assets/fonts/recoleta_medium.otf
          style: normal
          weight: 500
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/poppins_medium.ttf
          style: normal
          weight: 500

flavorizr:
  ide: "vscode"
  app:
    android:
      flavorDimensions: "flavor-type"

  flavors:
    dev:
      app:
        name: "FlutterBase (Dev)"

      android:
        applicationId: "com.flutterbase.dev"

      ios:
        bundleId: "com.flutterbase.dev"

    beta:
      app:
        name: "FlutterBase (Beta)"

      android:
        applicationId: "com.flutterbase.beta"
        firebase:
          config: ".firebase/beta/google-services.json"
        customConfig:
          signingConfig: signingConfigs.release_beta
      ios:
        bundleId: "com.flutterbase.beta"
        firebase:
          config: ".firebase/beta/GoogleService-Info.plist"

    live:
      app:
        name: "FlutterBase"

      android:
        applicationId: "com.flutterbase.live"
        firebase:
          config: ".firebase/live/google-services.json"
        customConfig:
          signingConfig: signingConfigs.release_live
      ios:
        bundleId: "com.flutterbase.live"
        firebase:
          config: ".firebase/live/GoogleService-Info.plist"
