name: flutter_base
description: Mr Milu's flutter base app.
publish_to: "none"

# We use the following build number guideline: yyyy+mm+dd+incremental
version: 0.0.1+202304051

environment:
  sdk: ^3.5.0

dependencies:
  browser_image_compression: 1.1.0
  cached_network_image: 3.4.0 # depends of firebase and web
  collection: 1.18.0 # depends integration test
  cross_file: 0.3.4+2
  crypto: 3.0.5
  dio: 5.6.0
  easy_localization: 3.0.7
  extended_image: 8.2.1
  faker_dart: 0.2.2
  firebase_auth: 5.1.4
  firebase_core: 3.3.0
  firebase_messaging: 15.0.4
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: 0.2.1
  flutter_cache_manager: 3.4.1
  flutter_config: 2.0.2 # maybe we can remove this (Published 13 months ago)
  flutter_dotenv: 5.1.0 # carefully with this, it's not updated (Published 14 months ago)
  flutter_image_compress: 2.3.0
  flutter_local_notifications: 17.2.2
  flutter_native_splash: 2.4.1
  flutter_riverpod: 2.5.1
  flutter_secure_storage: 9.2.2
  flutter_svg: 2.0.10+1
  freezed_annotation: 2.4.4
  get_it: 7.7.0
  go_router: 14.2.3
  google_sign_in: 6.2.1
  image: 4.2.0
  image_editor: 1.5.1
  image_picker: 1.1.2
  injectable: 2.4.4
  json_annotation: 4.9.0
  package_info_plus: 8.0.2
  path: 1.9.0
  path_provider: 2.1.4
  reactive_forms: 17.0.1
  reactive_forms_annotations: 5.0.0
  sentry_flutter: 8.7.0
  share_plus: 10.0.0 # depends of firebase and web
  sign_in_with_apple: 6.1.1
  stack_trace: 1.11.1 # carefully with this, it's neccesary?, it's not updated (Published 13 months ago)
  video_player: 2.9.1

dev_dependencies:
  build_runner: 2.4.12
  flutter_flavorizr: 2.2.3
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.7
  injectable_generator: 2.6.2
  integration_test:
    sdk: flutter
  json_serializable: 6.8.0
  mocktail: 1.0.4
  reactive_forms_generator: 5.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - .env.dev
    - .env.beta
    - .env.live

  fonts:
    - family: Recoleta
      fonts:
        - asset: assets/fonts/recoleta_medium.otf
          style: normal
          weight: 500
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/poppins_medium.ttf
          style: normal
          weight: 500

flavorizr:
  ide: "vscode"
  app:
    android:
      flavorDimensions: "flavor-type"

  flavors:
    dev:
      app:
        name: "FlutterBase (Dev)"

      android:
        applicationId: "com.flutterbase.dev"

      ios:
        bundleId: "com.flutterbase.dev"

    beta:
      app:
        name: "FlutterBase (Beta)"

      android:
        applicationId: "com.flutterbase.beta"
        firebase:
          config: ".firebase/beta/google-services.json"
        customConfig:
          signingConfig: signingConfigs.release_beta
      ios:
        bundleId: "com.flutterbase.beta"
        firebase:
          config: ".firebase/beta/GoogleService-Info.plist"

    live:
      app:
        name: "FlutterBase"

      android:
        applicationId: "com.flutterbase.live"
        firebase:
          config: ".firebase/live/google-services.json"
        customConfig:
          signingConfig: signingConfigs.release_live
      ios:
        bundleId: "com.flutterbase.live"
        firebase:
          config: ".firebase/live/GoogleService-Info.plist"
