import 'package:flutter/cupertino.dart';

import '../../../domain/types/prefix_phone_type.dart';
import '../buildcontext_extensions.dart';

extension PrefixPhoneTypeExtension on PrefixPhoneType {
  String toTranslate(BuildContext context) {
    switch (this) {
      case PrefixPhoneType.spain:
        return context.cl.translate('countries.ES');
      case PrefixPhoneType.germany:
        return context.cl.translate('countries.DE');
      case PrefixPhoneType.unitedKingdom:
        return context.cl.translate('countries.GB');
      case PrefixPhoneType.norway:
        return context.cl.translate('countries.NO');
      case PrefixPhoneType.sweden:
        return context.cl.translate('countries.SE');
      case PrefixPhoneType.finland:
        return context.cl.translate('countries.FI');
      case PrefixPhoneType.italy:
        return context.cl.translate('countries.IT');
      case PrefixPhoneType.portugal:
        return context.cl.translate('countries.PT');
      case PrefixPhoneType.france:
        return context.cl.translate('countries.FR');
      case PrefixPhoneType.afghanistan:
        return context.cl.translate('countries.AF');
      case PrefixPhoneType.albania:
        return context.cl.translate('countries.AL');
      case PrefixPhoneType.andorra:
        return context.cl.translate('countries.AD');
      case PrefixPhoneType.angola:
        return context.cl.translate('countries.AO');
      case PrefixPhoneType.antiguaAndBarbuda:
        return context.cl.translate('countries.AG');
      case PrefixPhoneType.saudiArabia:
        return context.cl.translate('countries.SA');
      case PrefixPhoneType.algeria:
        return context.cl.translate('countries.DZ');
      case PrefixPhoneType.argentina:
        return context.cl.translate('countries.AR');
      case PrefixPhoneType.armenia:
        return context.cl.translate('countries.AM');
      case PrefixPhoneType.australia:
        return context.cl.translate('countries.AU');
      case PrefixPhoneType.austria:
        return context.cl.translate('countries.AT');
      case PrefixPhoneType.azerbaijan:
        return context.cl.translate('countries.AZ');
      case PrefixPhoneType.bahamas:
        return context.cl.translate('countries.BS');
      case PrefixPhoneType.bangladesh:
        return context.cl.translate('countries.BD');
      case PrefixPhoneType.barbados:
        return context.cl.translate('countries.BB');
      case PrefixPhoneType.bahrain:
        return context.cl.translate('countries.BH');
      case PrefixPhoneType.belize:
        return context.cl.translate('countries.BZ');
      case PrefixPhoneType.benin:
        return context.cl.translate('countries.BJ');
      case PrefixPhoneType.belarus:
        return context.cl.translate('countries.BY');
      case PrefixPhoneType.myanmar:
        return context.cl.translate('countries.MM');
      case PrefixPhoneType.bolivia:
        return context.cl.translate('countries.BO');
      case PrefixPhoneType.bosniaAndHerzegovina:
        return context.cl.translate('countries.BA');
      case PrefixPhoneType.botswana:
        return context.cl.translate('countries.BW');
      case PrefixPhoneType.brazil:
        return context.cl.translate('countries.BR');
      case PrefixPhoneType.brunei:
        return context.cl.translate('countries.BN');
      case PrefixPhoneType.bulgaria:
        return context.cl.translate('countries.BG');
      case PrefixPhoneType.burkinaFaso:
        return context.cl.translate('countries.BF');
      case PrefixPhoneType.burundi:
        return context.cl.translate('countries.BI');
      case PrefixPhoneType.bhutan:
        return context.cl.translate('countries.BT');
      case PrefixPhoneType.belgium:
        return context.cl.translate('countries.BE');
      case PrefixPhoneType.capeVerde:
        return context.cl.translate('countries.CV');
      case PrefixPhoneType.cambodia:
        return context.cl.translate('countries.KH');
      case PrefixPhoneType.cameroon:
        return context.cl.translate('countries.CM');
      case PrefixPhoneType.canada:
        return context.cl.translate('countries.CA');
      case PrefixPhoneType.qatar:
        return context.cl.translate('countries.QA');
      case PrefixPhoneType.chad:
        return context.cl.translate('countries.TD');
      case PrefixPhoneType.chile:
        return context.cl.translate('countries.CL');
      case PrefixPhoneType.china:
        return context.cl.translate('countries.CN');
      case PrefixPhoneType.cyprus:
        return context.cl.translate('countries.CY');
      case PrefixPhoneType.vaticanCity:
        return context.cl.translate('countries.VA');
      case PrefixPhoneType.colombia:
        return context.cl.translate('countries.CO');
      case PrefixPhoneType.comoros:
        return context.cl.translate('countries.KM');
      case PrefixPhoneType.congo:
        return context.cl.translate('countries.CG');
      case PrefixPhoneType.northKorea:
        return context.cl.translate('countries.KP');
      case PrefixPhoneType.southKorea:
        return context.cl.translate('countries.KR');
      case PrefixPhoneType.costaRica:
        return context.cl.translate('countries.CR');
      case PrefixPhoneType.ivoryCoast:
        return context.cl.translate('countries.CI');
      case PrefixPhoneType.croatia:
        return context.cl.translate('countries.HR');
      case PrefixPhoneType.cuba:
        return context.cl.translate('countries.CU');
      case PrefixPhoneType.denmark:
        return context.cl.translate('countries.DK');
      case PrefixPhoneType.dominica:
        return context.cl.translate('countries.DM');
      case PrefixPhoneType.ecuador:
        return context.cl.translate('countries.EC');
      case PrefixPhoneType.egypt:
        return context.cl.translate('countries.EG');
      case PrefixPhoneType.elSalvador:
        return context.cl.translate('countries.SV');
      case PrefixPhoneType.unitedArabEmirates:
        return context.cl.translate('countries.AE');
      case PrefixPhoneType.eritrea:
        return context.cl.translate('countries.ER');
      case PrefixPhoneType.slovakia:
        return context.cl.translate('countries.SK');
      case PrefixPhoneType.slovenia:
        return context.cl.translate('countries.SI');
      case PrefixPhoneType.unitedStates:
        return context.cl.translate('countries.US');
      case PrefixPhoneType.estonia:
        return context.cl.translate('countries.EE');
      case PrefixPhoneType.eswatini:
        return context.cl.translate('countries.SZ');
      case PrefixPhoneType.ethiopia:
        return context.cl.translate('countries.ET');
      case PrefixPhoneType.philippines:
        return context.cl.translate('countries.PH');
      case PrefixPhoneType.fiji:
        return context.cl.translate('countries.FJ');
      case PrefixPhoneType.gabon:
        return context.cl.translate('countries.GA');
      case PrefixPhoneType.gambia:
        return context.cl.translate('countries.GM');
      case PrefixPhoneType.georgia:
        return context.cl.translate('countries.GE');
      case PrefixPhoneType.ghana:
        return context.cl.translate('countries.GH');
      case PrefixPhoneType.grenada:
        return context.cl.translate('countries.GD');
      case PrefixPhoneType.greece:
        return context.cl.translate('countries.GR');
      case PrefixPhoneType.guatemala:
        return context.cl.translate('countries.GT');
      case PrefixPhoneType.guinea:
        return context.cl.translate('countries.GN');
      case PrefixPhoneType.equatorialGuinea:
        return context.cl.translate('countries.GQ');
      case PrefixPhoneType.guineaBissau:
        return context.cl.translate('countries.GW');
      case PrefixPhoneType.guyana:
        return context.cl.translate('countries.GY');
      case PrefixPhoneType.haiti:
        return context.cl.translate('countries.HT');
      case PrefixPhoneType.honduras:
        return context.cl.translate('countries.HN');
      case PrefixPhoneType.hungary:
        return context.cl.translate('countries.HU');
      case PrefixPhoneType.india:
        return context.cl.translate('countries.IN');
      case PrefixPhoneType.indonesia:
        return context.cl.translate('countries.ID');
      case PrefixPhoneType.iraq:
        return context.cl.translate('countries.IQ');
      case PrefixPhoneType.ireland:
        return context.cl.translate('countries.IE');
      case PrefixPhoneType.iran:
        return context.cl.translate('countries.IR');
      case PrefixPhoneType.iceland:
        return context.cl.translate('countries.IS');
      case PrefixPhoneType.marshallIslands:
        return context.cl.translate('countries.MH');
      case PrefixPhoneType.solomonIslands:
        return context.cl.translate('countries.SB');
      case PrefixPhoneType.israel:
        return context.cl.translate('countries.IL');
      case PrefixPhoneType.jamaica:
        return context.cl.translate('countries.JM');
      case PrefixPhoneType.japan:
        return context.cl.translate('countries.JP');
      case PrefixPhoneType.jordan:
        return context.cl.translate('countries.JO');
      case PrefixPhoneType.kazakhstan:
        return context.cl.translate('countries.KZ');
      case PrefixPhoneType.kenya:
        return context.cl.translate('countries.KE');
      case PrefixPhoneType.kyrgyzstan:
        return context.cl.translate('countries.KG');
      case PrefixPhoneType.kiribati:
        return context.cl.translate('countries.KI');
      case PrefixPhoneType.kuwait:
        return context.cl.translate('countries.KW');
      case PrefixPhoneType.laos:
        return context.cl.translate('countries.LA');
      case PrefixPhoneType.lesotho:
        return context.cl.translate('countries.LS');
      case PrefixPhoneType.latvia:
        return context.cl.translate('countries.LV');
      case PrefixPhoneType.liberia:
        return context.cl.translate('countries.LR');
      case PrefixPhoneType.libya:
        return context.cl.translate('countries.LY');
      case PrefixPhoneType.liechtenstein:
        return context.cl.translate('countries.LI');
      case PrefixPhoneType.lithuania:
        return context.cl.translate('countries.LT');
      case PrefixPhoneType.luxembourg:
        return context.cl.translate('countries.LU');
      case PrefixPhoneType.lebanon:
        return context.cl.translate('countries.LB');
      case PrefixPhoneType.madagascar:
        return context.cl.translate('countries.MG');
      case PrefixPhoneType.malaysia:
        return context.cl.translate('countries.MY');
      case PrefixPhoneType.malawi:
        return context.cl.translate('countries.MW');
      case PrefixPhoneType.maldives:
        return context.cl.translate('countries.MV');
      case PrefixPhoneType.malta:
        return context.cl.translate('countries.MT');
      case PrefixPhoneType.mali:
        return context.cl.translate('countries.ML');
      case PrefixPhoneType.morocco:
        return context.cl.translate('countries.MA');
      case PrefixPhoneType.mauritius:
        return context.cl.translate('countries.MU');
      case PrefixPhoneType.mauritania:
        return context.cl.translate('countries.MR');
      case PrefixPhoneType.micronesia:
        return context.cl.translate('countries.FM');
      case PrefixPhoneType.moldova:
        return context.cl.translate('countries.MD');
      case PrefixPhoneType.mongolia:
        return context.cl.translate('countries.MN');
      case PrefixPhoneType.montenegro:
        return context.cl.translate('countries.ME');
      case PrefixPhoneType.mozambique:
        return context.cl.translate('countries.MZ');
      case PrefixPhoneType.mexico:
        return context.cl.translate('countries.MX');
      case PrefixPhoneType.monaco:
        return context.cl.translate('countries.MC');
      case PrefixPhoneType.namibia:
        return context.cl.translate('countries.NA');
      case PrefixPhoneType.nauru:
        return context.cl.translate('countries.NR');
      case PrefixPhoneType.nepal:
        return context.cl.translate('countries.NP');
      case PrefixPhoneType.nicaragua:
        return context.cl.translate('countries.NI');
      case PrefixPhoneType.nigeria:
        return context.cl.translate('countries.NG');
      case PrefixPhoneType.newZealand:
        return context.cl.translate('countries.NZ');
      case PrefixPhoneType.niger:
        return context.cl.translate('countries.NE');
      case PrefixPhoneType.oman:
        return context.cl.translate('countries.OM');
      case PrefixPhoneType.pakistan:
        return context.cl.translate('countries.PK');
      case PrefixPhoneType.palau:
        return context.cl.translate('countries.PW');
      case PrefixPhoneType.panama:
        return context.cl.translate('countries.PA');
      case PrefixPhoneType.papuaNewGuinea:
        return context.cl.translate('countries.PG');
      case PrefixPhoneType.paraguay:
        return context.cl.translate('countries.PY');
      case PrefixPhoneType.netherlands:
        return context.cl.translate('countries.NL');
      case PrefixPhoneType.peru:
        return context.cl.translate('countries.PE');
      case PrefixPhoneType.poland:
        return context.cl.translate('countries.PL');
      case PrefixPhoneType.centralAfricanRepublic:
        return context.cl.translate('countries.CF');
      case PrefixPhoneType.czechRepublic:
        return context.cl.translate('countries.CZ');
      case PrefixPhoneType.democraticRepublicOfCongo:
        return context.cl.translate('countries.CD');
      case PrefixPhoneType.dominicanRepublic:
        return context.cl.translate('countries.DO');
      case PrefixPhoneType.republicOfCongo:
        return context.cl.translate('countries.RC');
      case PrefixPhoneType.rwanda:
        return context.cl.translate('countries.RW');
      case PrefixPhoneType.romania:
        return context.cl.translate('countries.RO');
      case PrefixPhoneType.russia:
        return context.cl.translate('countries.RU');
      case PrefixPhoneType.samoa:
        return context.cl.translate('countries.WS');
      case PrefixPhoneType.saintKittsAndNevis:
        return context.cl.translate('countries.KN');
      case PrefixPhoneType.sanMarino:
        return context.cl.translate('countries.SM');
      case PrefixPhoneType.saintVincentAndGrenadines:
        return context.cl.translate('countries.VC');
      case PrefixPhoneType.saintLucia:
        return context.cl.translate('countries.LC');
      case PrefixPhoneType.saoTomeAndPrincipe:
        return context.cl.translate('countries.ST');
      case PrefixPhoneType.senegal:
        return context.cl.translate('countries.SN');
      case PrefixPhoneType.serbia:
        return context.cl.translate('countries.RS');
      case PrefixPhoneType.seychelles:
        return context.cl.translate('countries.SC');
      case PrefixPhoneType.sierraLeone:
        return context.cl.translate('countries.SL');
      case PrefixPhoneType.singapore:
        return context.cl.translate('countries.SG');
      case PrefixPhoneType.syria:
        return context.cl.translate('countries.SY');
      case PrefixPhoneType.somalia:
        return context.cl.translate('countries.SO');
      case PrefixPhoneType.sriLanka:
        return context.cl.translate('countries.LK');
      case PrefixPhoneType.southAfrica:
        return context.cl.translate('countries.ZA');
      case PrefixPhoneType.sudan:
        return context.cl.translate('countries.SD');
      case PrefixPhoneType.southSudan:
        return context.cl.translate('countries.SS');
      case PrefixPhoneType.switzerland:
        return context.cl.translate('countries.CH');
      case PrefixPhoneType.suriname:
        return context.cl.translate('countries.SR');
      case PrefixPhoneType.thailand:
        return context.cl.translate('countries.TH');
      case PrefixPhoneType.tanzania:
        return context.cl.translate('countries.TZ');
      case PrefixPhoneType.tajikistan:
        return context.cl.translate('countries.TJ');
      case PrefixPhoneType.eastTimor:
        return context.cl.translate('countries.TL');
      case PrefixPhoneType.togo:
        return context.cl.translate('countries.TG');
      case PrefixPhoneType.tonga:
        return context.cl.translate('countries.TO');
      case PrefixPhoneType.trinidadAndTobago:
        return context.cl.translate('countries.TT');
      case PrefixPhoneType.turkmenistan:
        return context.cl.translate('countries.TM');
      case PrefixPhoneType.turkey:
        return context.cl.translate('countries.TR');
      case PrefixPhoneType.tuvalu:
        return context.cl.translate('countries.TV');
      case PrefixPhoneType.tunisia:
        return context.cl.translate('countries.TN');
      case PrefixPhoneType.ukraine:
        return context.cl.translate('countries.UA');
      case PrefixPhoneType.uganda:
        return context.cl.translate('countries.UG');
      case PrefixPhoneType.uruguay:
        return context.cl.translate('countries.UY');
      case PrefixPhoneType.uzbekistan:
        return context.cl.translate('countries.UZ');
      case PrefixPhoneType.vanuatu:
        return context.cl.translate('countries.VU');
      case PrefixPhoneType.venezuela:
        return context.cl.translate('countries.VE');
      case PrefixPhoneType.vietnam:
        return context.cl.translate('countries.VN');
      case PrefixPhoneType.yemen:
        return context.cl.translate('countries.YE');
      case PrefixPhoneType.djibouti:
        return context.cl.translate('countries.DJ');
      case PrefixPhoneType.zambia:
        return context.cl.translate('countries.ZM');
      case PrefixPhoneType.zimbabwe:
        return context.cl.translate('countries.ZW');
    }
  }
}
