/// Flutter icons MoggieIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MoggieIcons
///      fonts:
///       - asset: fonts/MoggieIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MoggieIcons {
  MoggieIcons._();

  static const _kFontFam = 'MoggieIcons';
  static const String? _kFontPkg = null;

  static const IconData placeholder_line = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down_lime = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_line = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData immediate_care_line = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_line = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross_line = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_line = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData less_line = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData virtual_assitant_line = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bin_line = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData options_line = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_line = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_line = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_line = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_line = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_line = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_line = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute_line = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_line = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_line = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up_line = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badge_line = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi_line = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth_line = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_line = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_line = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_line = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_line = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card_line = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_line = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery_line = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_line = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health_line = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right_line = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_line = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_line = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left_line = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_line = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_line = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat_line = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound_line = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left_line = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_line = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_filled = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paw_small_filled = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_filled = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_filled = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_filled = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_filled = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_filled = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_filled = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health_alt_filled = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_filled = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_small_filled = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health_filled = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paw_filled = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_small_filled = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_line = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paw_line = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password_line = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
