# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build and deploy a new version to the Google Play"
  lane :build_deploy_beta do
    sh("fvm", "flutter", "build", "appbundle", "--flavor", "beta", "./lib/main_beta.dart")
    upload_to_play_store(
      package_name: 'com.flutterbase-mrmilu.beta',
      track: 'internal',
      aab: '../build/app/outputs/bundle/betaRelease/app-beta-release.aab'
    )
  end
end
