plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
    id("com.google.gms.google-services")
}

import java.util.Properties
import java.io.FileInputStream

val betaKeystoreProperties = Properties()
val betaKeystorePropertiesFile = rootProject.file("beta.key.properties")
if (betaKeystorePropertiesFile.exists()) {
    betaKeystoreProperties.load(FileInputStream(betaKeystorePropertiesFile))
}

val liveKeystoreProperties = Properties()
val liveKeystorePropertiesFile = rootProject.file("live.key.properties")
if (liveKeystorePropertiesFile.exists()) {
    liveKeystoreProperties.load(FileInputStream(liveKeystorePropertiesFile))
}

android {
    signingConfigs {
        create("release_beta") {
            keyAlias = betaKeystoreProperties["keyAlias"] as String?
            keyPassword = betaKeystoreProperties["keyPassword"] as String?
            storeFile = betaKeystoreProperties["storeFile"]?.let { file(it as String) }
            storePassword = betaKeystoreProperties["storePassword"] as String?
        }
        create("release_live") {
            keyAlias = liveKeystoreProperties["keyAlias"] as String?
            keyPassword = liveKeystoreProperties["keyPassword"] as String?
            storeFile = liveKeystoreProperties["storeFile"]?.let { file(it as String) }
            storePassword = liveKeystoreProperties["storePassword"] as String?
        }
    }

    namespace = "com.flutterbase.live.flutter_base"
    compileSdk = 35
    // ndkVersion = flutter.ndkVersion

    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.flutterbase.live.flutter_base"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = 24
        targetSdk = 35
        versionCode = flutter.versionCode
        versionName = flutter.versionName

        resourceConfigurations.addAll(listOf("es", "en", "ca", "eu", "gl"))
    }

    buildTypes {
        getByName("release") {
            isShrinkResources = true
            isMinifyEnabled = true
            proguardFiles(
                getDefaultProguardFile("proguard-android.txt"),
                "proguard-rules.pro"
            )
        }
    }
}

flutter {
    source = "../.."
}

dependencies {
  // Import the Firebase BoM
  implementation(platform("com.google.firebase:firebase-bom:33.16.0"))
  coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
}

// ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
apply { from("flavorizr.gradle.kts") }
// ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----