name: build_ios

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "develop"
    paths:
      - "pubspec.yaml"

jobs:
  build-and-deploy:
    environment:
      name: ${{ github.ref_name == 'master' && 'live' || 'beta'}}
    runs-on: macos-15
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      FASTLIGHT_APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.FASTLIGHT_APP_STORE_CONNECT_PRIVATE_KEY }}
      ENVIRONMENT: ${{ github.ref_name == 'master' && 'live' || 'beta'}}
    steps:
      - name: Setup iOS certificates repository SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Reading FVM
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Dar permisos de ejecución al script
        run: chmod +x extract_name@version.sh

      - name: Extract app version
        run: echo "APP_VERSION=$(./extract_name@version.sh)" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          architecture: x64

      - name: Dependencies
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter pub run intl_utils:generate

      - name: iOS setup
        working-directory: ios
        run: |
          flutter precache --ios
          bundle install
          pod install

      - name: Run lane
        run: bundle exec fastlane build_deploy_internal_${{ env.ENVIRONMENT }}
        working-directory: ios

      - name: Send deploy status to Slack
        if: always()
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C08M356URCH"
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":apple: iOS deploy result for *${{ env.ENVIRONMENT }}*: ${{ job.status == 'failure' && ':boom: *Failure!!*' || job.status == 'success' && ':white_check_mark: *Success!!*' || ':hand: *Cancelled*'}} \n *Version:* ${{ env.APP_VERSION }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
